oro_menu_config:
    items:
        system_configuraion:
            label: 'Configuration'
            extras:
                description: 'System configuration'
            route: 'oro_config_configuration_system'

    tree:
        application_menu:
            children:
                system_tab:
                    children:
                        system_configuraion: ~

oro_titles:
    oro_config_configuration_system: ~
