config:
    paths:
        'oroconfig/js/form/state':   'bundles/oroconfig/js/form/state.js'
        'oroconfig/js/form/default': 'bundles/oroconfig/js/form/default.js'
        'oroconfig/js/app/components/color-table': 'bundles/oroconfig/js/app/components/color-table.js'
