parameters:
    oro_config.user.class:                                                       Oro\Bundle\ConfigBundle\Config\UserConfigManager
    oro_config.twig_extension.class:                                             Oro\Bundle\ConfigBundle\Twig\ConfigExtension
    oro_config.provider.system_configuration.form_provider.class:                Oro\Bundle\ConfigBundle\Provider\SystemConfigurationFormProvider
    oro_config.type.form.class:                                                  Oro\Bundle\ConfigBundle\Form\Type\FormType
    oro_config.form.handler.config.class:                                        Oro\Bundle\ConfigBundle\Form\Handler\ConfigHandler

services:
    oro_config.user:
        class:                        %oro_config.user.class%
        arguments:                    ["@doctrine.orm.entity_manager"]
        calls:
             - [setSecurity, ["@security.context"]]
        tags:
            -  { name: oro_config.manager }

    oro_config.twig.config_extension:
        class:                        %oro_config.twig_extension.class%
        arguments:                    ["@oro_config.user", %oro_config.entities%]
        tags:
            - { name: twig.extension }

    oro_config.provider.system_configuration.form_provider:
        class:                        %oro_config.provider.system_configuration.form_provider.class%
        arguments:
            - []
            - @form.factory
        tags:
            -  { name: oro_config.configuration_form_provider }

    oro_config.type.form:
        class:                        %oro_config.type.form.class%
        tags:
            - { name: form.type, alias: oro_config_form_type }

    oro_config.form.handler.config:
        class: %oro_config.form.handler.config.class%
        scope: request
        arguments:
            - @request
            - @oro_config.user
