oro_system_configuration:
    scopes:
       - global

    groups:
        platform:
            title: 'Platform'
            icon:  icon-hdd

        general_setup:
            title: 'General setup'

        application_information:
            title: 'Application information'
            priority: 20

        localization:
            title: 'Localization'
            icon:  icon-time
            description: 'Some additional information about possible localization setup and real need of localization settings (help block)'
            priority: 10

        locale_options:
            title: 'Locale options'

        sales:
            title: 'Sales'

    fields:
        oro_user.date_format:
            type: text
            options:
               label: 'Date format'
               required: true
               constraints:
                  - NotBlank: ~

            scopes: [ global ]
            priority: 10

    tree:
        system_configuration:
            sales:
                children: []
                priority: 10
            platform:
                priority: 20
                children:
                    general_setup:
                        priority: 10
                        children:
                            application_information:
                                children: []
                            localization:
                                children:
                                    locale_options:
                                        children:
                                            - oro_user.date_format
